In [3]:

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
from scipy import stats
import statsmodels.formula.api as smf
%matplotlib inline
import matplotlib.pyplot as plt

import pickle

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, RFE, mutual_info_classif

pd.options.mode.chained_assignment = None
# Set pandas options to display all columns
pd.set_option('display.max_columns', None)
import requests
from bs4 import BeautifulSoup

data sources:

basic player stats - money puck/Natural stat trick
split team stats - natural stat trick
player ages - natural stat trick player bios

In [5]:
#All dataframes have the season ending year
all_players_24 = pd.read_csv("skaters_2024.csv")
mult_teams_24 = pd.read_csv("split_times_2024.csv")
goals_24 = pd.read_csv("goals_2024.csv")

all_players_23 = pd.read_csv("skaters_2023.csv")
mult_teams_23 = pd.read_csv("split_times_2023.csv")
goals_23 = pd.read_csv("goals_2023.csv")

all_players_22 = pd.read_csv("skaters_2022.csv")
mult_teams_22 = pd.read_csv("split_times_2022.csv")
goals_22 = pd.read_csv("goals_2022.csv")

ages_22 = pd.read_csv("player_ages_22.csv")
ages_23 = pd.read_csv("player_ages_23.csv")
ages_24= pd.read_csv("player_ages_24.csv")

In [6]:
players = goals_24[['Player', 'Position','GP', 'IPP', 'ixG', 'Goals', 'Total Points', 'iCF']]
players['season_end'] = 2024
players = players.rename(columns={'GP': 'gp_2024'})
players.head()

,Player,Position,gp_2024,IPP,ixG,Goals,Total Points,iCF,season_end
0,Nikita Kucherov,R,81,82.76,32.59,44,144,635,2024
1,Nathan MacKinnon,C,82,74.87,34.82,51,140,692,2024
2,Connor McDavid,C,76,79.04,33.15,32,132,452,2024
3,Artemi Panarin,L,82,80.00,28.44,49,120,651,2024
4,David Pastrnak,R,82,80.88,37.42,47,110,718,2024

In [7]:
players = pd.merge(players, all_players_23[['Player', 'GP']], on='Player')
players = players.rename(columns={'GP': 'gp_2023'})
players

,Player,Position,gp_2024,IPP,ixG,Goals,Total Points,iCF,season_end,gp_2023
0,Nikita Kucherov,R,81,82.76,32.59,44,144,635,2024,82
1,Nathan MacKinnon,C,82,74.87,34.82,51,140,692,2024,71
2,Connor McDavid,C,76,79.04,33.15,32,132,452,2024,82
3,Artemi Panarin,L,82,80.00,28.44,49,120,651,2024,82
4,David Pastrnak,R,82,80.88,37.42,47,110,718,2024,82
...,...,...,...,...,...,...,...,...,...,...
772,Lucas Condotta,L,3,0.00,0.22,0,0,3,2024,1
773,Filip Roos,D,4,0.00,0.02,0,0,7,2024,17
774,Pavol Regenda,L,5,-,0.49,0,0,10,2024,14
775,Akito Hirose,D,3,0.00,0.00,0,0,1,2024,7
776,Cole McWard,D,1,-,0.14,0,0,4,2024,5

In [8]:

players = pd.merge(players, all_players_22[['Player', 'GP']], on='Player')
players = players.rename(columns={'GP': 'gp_2022'})
players

,Player,Position,gp_2024,IPP,ixG,Goals,Total Points,iCF,season_end,gp_2023,gp_2022
0,Nikita Kucherov,R,81,82.76,32.59,44,144,635,2024,82,47
1,Nathan MacKinnon,C,82,74.87,34.82,51,140,692,2024,71,65
2,Connor McDavid,C,76,79.04,33.15,32,132,452,2024,82,80
3,Artemi Panarin,L,82,80.00,28.44,49,120,651,2024,82,75
4,David Pastrnak,R,82,80.88,37.42,47,110,718,2024,82,72
...,...,...,...,...,...,...,...,...,...,...,...
686,Victor Soderstrom,D,3,0.00,0.04,0,0,4,2024,30,16
687,Tobias Bjornfot,D,4,-,0.01,0,0,3,2024,10,70
688,Connor Mackey,D,1,0.00,0.01,0,0,2,2024,30,3
689,Adam Raska,R,5,0.00,0.00,0,0,0,2024,3,5
690,Alex Steeves,C,1,-,0.32,0,0,3,2024,3,3

In [9]:
players=players.sort_values(by=['gp_2024'], ascending=[False]).reset_index()
players=players.drop('index', axis = 1)
players.head()

,Player,Position,gp_2024,IPP,ixG,Goals,Total Points,iCF,season_end,gp_2023,gp_2022
0,Sean Monahan,C,83,55.66,25.04,26,59,297,2024,25,65
1,Cole Caufield,R,82,60.75,32.38,28,65,564,2024,46,67
2,Lars Eller,C,82,62.00,17.82,15,31,299,2024,84,72
3,Ivan Barbashev,C,82,52.94,16.96,19,45,236,2024,82,81
4,Trent Frederic,C,82,75.47,17.36,18,40,230,2024,79,60

### Player Usage

In [11]:
individual_stats = all_players_24[['Player', 'CF', 'CA', 'GF', 'GA', 'GF%', 'xGF', 'xGA', 'HDGF%', 'PDO']]
goals = goals_24[['Player', 'Goals', 'Total Assists', 'First Assists', 'Second Assists', 'Total Points', 'IPP', 'Shots', 'SH%', 'ixG', 'iCF', 'iHDCF', 'Rush Attempts','Rebounds Created', 'Giveaways', 'Takeaways', 'Hits', 'Hits Taken', 'Shots Blocked', 'Faceoffs %']]
player_stats = goals.merge(individual_stats, on="Player")
player_stats.head()

,Player,Goals,Total Assists,First Assists,Second Assists,Total Points,IPP,Shots,SH%,ixG,iCF,iHDCF,Rush Attempts,Rebounds Created,Giveaways,Takeaways,Hits,Hits Taken,Shots Blocked,Faceoffs %,CF,CA,GF,GA,GF%,xGF,xGA,HDGF%,PDO
0,Nikita Kucherov,44,100,62,38,144,82.76,306,14.38,32.59,635,87,6,44,96,62,42,73,35,50.00,2299,1465,174,103,62.82,135.87,87.21,61.48,1.020
1,Nathan MacKinnon,51,89,50,39,140,74.87,405,12.59,34.82,692,103,29,45,82,42,49,80,69,46.19,2587,1528,187,88,68.00,144.48,79.83,68.84,1.028
2,Connor McDavid,32,100,62,38,132,79.04,263,12.17,33.15,452,115,11,46,84,68,107,120,39,51.10,2242,1237,167,82,67.07,146.79,70.14,72.09,1.020
3,Artemi Panarin,49,71,37,34,120,80.00,303,16.17,28.44,651,66,13,50,72,34,16,38,15,10.00,2344,1306,150,73,67.26,134.89,73.56,59.26,1.026
4,David Pastrnak,47,63,39,24,110,80.88,382,12.30,37.42,718,105,24,60,98,54,63,133,19,33.33,1965,1366,136,68,66.67,118.40,69.76,65.14,1.036

In [12]:


# Function to scrape data for a specific season and situation (pp for powerplay, pk for penalty kill)
def scrape_season_data(from_season, thru_season, sit):
    url = f"https://naturalstattrick.com/playerteams.php?fromseason={from_season}&thruseason={thru_season}&stype=2&sit={sit}&score=all&stdoi=std&rate=n&team=ALL&pos=S&loc=B&toi=0&gpfilt=none&fd=&td=&tgp=410&lines=multi&draftteam=ALL"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    
    # Find the table
    table = soup.find('table')
    
    # Extract headers
    headers = [header.text for header in table.find_all('th')]
    
    # Extract rows
    rows = []
    for row in table.find_all('tr')[1:]:  # Skip header row
        rows.append([cell.text for cell in row.find_all('td')])
    
    # Create a DataFrame
    df = pd.DataFrame(rows, columns=headers)
    return df

# Define seasons
seasons = [(20212022, 20212022), (20222023, 20222023), (20232024, 20232024)]

# Scrape data for powerplay and penalty kill for each season
powerplay_dfs = []
penaltykill_dfs = []

for from_season, thru_season in seasons:
    powerplay_df = scrape_season_data(from_season, thru_season, 'pp')
    penaltykill_df = scrape_season_data(from_season, thru_season, 'pk')
    powerplay_df['Season'] = f"{from_season}-{thru_season}"
    penaltykill_df['Season'] = f"{from_season}-{thru_season}"
    powerplay_dfs.append(powerplay_df)
    penaltykill_dfs.append(penaltykill_df)

# Combine data for all seasons
all_powerplay_data = pd.concat(powerplay_dfs, ignore_index=True)
all_penaltykill_data = pd.concat(penaltykill_dfs, ignore_index=True)

# Save to CSV
all_powerplay_data.to_csv('powerplay_data.csv', index=False)
all_penaltykill_data.to_csv('penaltykill_data.csv', index=False)

print("Scraping complete. Data saved to 'powerplay_data.csv' and 'penaltykill_data.csv'.")

Scraping complete. Data saved to 'powerplay_data.csv' and 'penaltykill_data.csv'.

In [13]:
all_powerplay_data.head()

,,Player,Team,Position,GP,TOI,Goals,Total Assists,First Assists,Second Assists,Total Points,IPP,Shots,SH%,ixG,iCF,iFF,iSCF,iHDCF,Rush Attempts,Rebounds Created,PIM,Total Penalties,Minor,Major,Misconduct,Penalties Drawn,Giveaways,Takeaways,Hits,Hits Taken,Shots Blocked,Faceoffs Won,Faceoffs Lost,Faceoffs %,Season
0,1,Zdeno Chara,NYI,D,72,4.7833333333333,0,0,0,0,0,0.00,0,-,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-,20212022-20212022
1,2,Joe Thornton,FLA,C,34,44.633333333333,3,0,0,0,3,75.00,6,50.00,0.89,12,9,8,3,0,0,2,1,1,0,0,0,0,1,1,0,0,6,7,46.15,20212022-20212022
2,3,Jason Spezza,TOR,C,71,101.78333333333,3,7,5,2,10,71.43,17,17.65,1.96,34,23,16,2,0,5,6,3,3,0,0,0,3,0,0,2,0,43,35,55.13,20212022-20212022
3,4,Duncan Keith,EDM,D,64,41.116666666667,0,2,0,2,2,66.67,3,0.00,0.25,8,5,2,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,-,20212022-20212022
4,5,Ryan Suter,DAL,D,82,172.5,4,9,2,7,13,68.42,26,15.38,1.93,44,32,13,3,1,2,4,2,2,0,0,0,0,1,0,3,0,0,0,-,20212022-20212022

In [29]:
# Store datasets in lists
ages_list = [ages_22, ages_23, ages_24]
player_usage_list = [all_players_22, all_players_23, all_players_24]
multi_teams_list = [mult_teams_22, mult_teams_23, mult_teams_24]
goals_list = [goals_22, goals_23, goals_24]

# Function to process each dataset
def process_data(ages, all_players, multi_teams, goals):

    individual_stats = all_players[['Player', 'CF', 'CA', 'GF', 'GA', 'GF%', 'xGF', 'xGA', 'HDGF%', 'PDO']]
    goals = goals[['Player', 'Goals', 'Total Assists', 'First Assists', 'Second Assists', 'Total Points', 'IPP', 'Shots', 'SH%', 'ixG', 'iCF', 'iHDCF', 'Rush Attempts','Rebounds Created', 'Giveaways', 'Takeaways', 'Hits', 'Hits Taken', 'Shots Blocked', 'Faceoffs %']]
    player_stats = goals.merge(individual_stats, on="Player")
    
    # All Players usage to calculate the overall percentile
    all_toi = all_players[['Player', 'Team', 'Position', 'GP', 'TOI']]
    all_toi = all_toi.query('GP >= 30')
    all_toi.loc[:, 'TOI'] = round(all_toi['TOI'], 2)

    #add in player ages
    all_toi = all_toi.merge(ages, on=('Player', 'Position'), how='left')
    all_toi = all_toi[['Player', 'Team_x', 'Position', 'GP', 'TOI', 'Age']]
    all_toi = all_toi.rename(columns={'Team_x': 'Team'})       

    
    #redefine the dataframe
    all_toi = all_toi[['Player', 'Team', 'Position', 'GP', 'TOI', 'Age']]
    all_toi['atoi'] =round((all_toi['TOI']/all_toi['GP']),2)

    # Total TOI Percentile
    all_toi['total_percentile'] = all_toi['TOI'].rank(pct=True)
    all_toi['Skater'] = np.where(all_toi['Position'] == "D", "D", "F")

    # Multi-team players
    multiple_teams = all_toi.query('Team.str.contains(",")')
    multiple_teams = multiple_teams.explode('Team').reset_index(drop=True)
    multi_teams = multi_teams[['Player', 'Team', 'GP', 'TOI']]
    multi_teams['atoi'] = round((multi_teams['TOI']/multi_teams['GP']),2)
    multi_teams['TOI'] = round(multi_teams['TOI'],2)
    multi_teams = multi_teams[multi_teams.duplicated('Player', keep=False)]
    multi_teams = multi_teams.sort_values(by=['Player', 'GP'], ascending=[True, False]).reset_index()

    
    #Creating a new df of just the multi team players with their total TOI and overal percentile.
    multiple_teams = multiple_teams.merge(multi_teams, on="Player", how="left")
    multiple_teams = multiple_teams[['Player', 'Team_y', 'Position', 'GP_x', 'GP_y', 'TOI_x', 'TOI_y', 'atoi_x', 'atoi_y', 'Age', 'total_percentile', 'Skater' ]]
    multiple_teams = multiple_teams.rename(columns={'Team_y': 'Team',
                                       'TOI_x':'TOI', 'TOI_y':'team_TOI', 'GP_x':'GP', 'GP_y':'team_gp', 'atoi_x':'atoi', 'atoi_y':'team_atoi'})

    
    
    # Single-team players
    single_teams = all_toi.query('~Team.str.contains(",")')
    all_players = pd.concat([single_teams, multiple_teams], ignore_index=True)

    #join the multi team players back in 
    all_players['team_TOI'] = np.where(pd.isnull(all_players['team_TOI']), all_players['TOI'], all_players['team_TOI'])
    all_players['team_gp'] = np.where(pd.isnull(all_players['team_gp']), all_players['GP'], all_players['team_gp'])
    all_players['team_atoi'] = np.where(all_players['team_atoi'].isnull(), all_players['atoi'],all_players['team_atoi'])
    all_players['adj_toi'] = all_players['team_atoi']*all_players['GP']

# Quality of Team - Rank Among Forwards
    def calculate_percentile_rank_f(player_time_on_ice, player_position, player_team):
        filtered_data = all_players[(all_players["Skater"] == "F") & (all_players["Team"] == player_team)]
        forwards_time_on_ice = filtered_data["adj_toi"]
        return stats.percentileofscore(forwards_time_on_ice, player_time_on_ice)

    all_players["QoTF"] = all_players.apply(lambda row: calculate_percentile_rank_f(row["adj_toi"], row["Skater"], row["Team"]), axis=1)

    # Quality of Team - Rank Among Defensemen
    def calculate_percentile_rank_d(player_time_on_ice, player_position, player_team):
        filtered_data = all_players[(all_players["Skater"] == "D") & (all_players["Team"] == player_team)]
        defense_time_on_ice = filtered_data["adj_toi"]
        return stats.percentileofscore(defense_time_on_ice, player_time_on_ice)

    all_players["QoTD"] = all_players.apply(lambda row: calculate_percentile_rank_d(row["adj_toi"], row["Skater"], row["Team"]), axis=1)

        # Specific name to keep
    name_to_keep = 'Sebastian Aho'
    duplicates_except_specific = all_players[all_players['Player'] != name_to_keep]
    duplicated_names = duplicates_except_specific[duplicates_except_specific.duplicated(subset='Player')]['Player']
    result_df = all_players[all_players['Player'].isin(duplicated_names)]
    
    #Adding a column to identify the team that the player started with and then ended with
    result_df.loc[:, 'team_no'] = result_df.groupby('Player').cumcount() + 1
    pivoted_df = result_df.pivot(index='Player', columns='team_no', values=['Team', 'adj_toi'])
    pivoted_df.columns = [f'{col[0]} {col[1]}' for col in pivoted_df.columns]
    pivoted_df.reset_index(inplace=True)
    pivoted_df = pivoted_df.fillna(0)
    all_players = all_players.merge(pivoted_df, on="Player", how="left")

    # Quality of Competition - Forwards
    def calculate_qoc_f(player_row):
        filtered_data = all_players[(all_players["Skater"] == "F") & (all_players["Player"] != player_row["Player"]) & (all_players["Team"] != player_row["Team"])]
        grouped_data = filtered_data.groupby("Player")["adj_toi"].mean()
        return stats.percentileofscore(grouped_data, player_row["adj_toi"])

    all_players["QoCF"] = all_players.apply(lambda row: calculate_qoc_f(row), axis=1)

    # Quality of Competition - Defense
    def calculate_qoc_d(player_row):
        filtered_data = all_players[(all_players["Skater"] == "D") & (all_players["Player"] != player_row["Player"]) & (all_players["Team"] != player_row["Team"])]
        grouped_data = filtered_data.groupby("Player")["adj_toi"].mean()
        return stats.percentileofscore(grouped_data, player_row["adj_toi"])

    all_players["QoCD"] = all_players.apply(lambda row: calculate_qoc_d(row), axis=1)

    all_players['team_no'] = all_players.groupby('Player').cumcount() + 1
    all_players['team_count'] = np.where(pd.isnull(all_players['Team 1']), all_players['Team'], "Multi")

    mult_team_quals = all_players.query('team_count == "Multi"')
    mult_team_quals.loc[:, 'team_no'] = mult_team_quals.groupby('Player').cumcount() + 1

    # Pivot the DataFrame to reshape it and include QoC
    pivot_competition_f = mult_team_quals.pivot(index='Player', columns='team_no', values=['Team', 'adj_toi', 'QoCF', 'QoTF'])
    pivot_competition_d = mult_team_quals.pivot(index='Player', columns='team_no', values=['Team', 'adj_toi', 'QoCD', 'QoTD'])
    
    # Rename columns to 'Team 1', 'Team 2', 'TOI Team 1', 'TOI Team 2', etc.
    pivot_competition_f.columns = [f'{col[0]} {col[1]}' for col in pivot_competition_f.columns]
    pivot_competition_d.columns = [f'{col[0]} {col[1]}' for col in pivot_competition_d.columns]

    # Reset index to make 'Player' a column again
    pivot_competition_f.reset_index(inplace=True)
    pivot_competition_d.reset_index(inplace=True)

    # Replace NaN values with 0
    pivot_competition_f = pivot_competition_f.fillna(0)
    pivot_competition_d = pivot_competition_d.fillna(0)

    
    # Select and rename columns as required for final output
    pivot_competition_d = pivot_competition_d[['Player', 'QoCD 1', 'QoCD 2', 'QoCD 3', 'QoTD 1', 'QoTD 2', 'QoTD 3']]

    # Merge the pivoted DataFrames back together
    weighted_df = pd.merge(pivot_competition_f, pivot_competition_d, on='Player')

    # Identify the specific name to keep (the one with two different players)
    name_to_keep = 'Sebastian Aho'

    # Create a mask to keep the first occurrence of all player names except for the specific name
    mask = all_players['Player'] != name_to_keep
    filtered_players = all_players[mask].drop_duplicates(subset='Player', keep='first')

    # Append the rows with the specific name to the filtered DataFrame
    filtered_players = pd.concat([filtered_players, all_players], ignore_index=True).drop_duplicates()

    player_usage = filtered_players.merge(weighted_df, on="Player", how="left")

    player_usage['total_percentile'] = round(player_usage['total_percentile'] * 100, 2)
    columns_to_round = ['QoCF', 'QoCD', 'QoTF', 'QoTD']

    player_usage[columns_to_round] = player_usage[columns_to_round].apply(lambda x: round(x, 2))

    player_usage['toughest_min'] = player_usage['QoCF']+player_usage['QoCD']+player_usage['QoTF']+player_usage['QoTD'] 

    player_usage = player_usage.sort_values(['toughest_min', 'TOI'], ascending=[False, False]).reset_index(drop=True)

    player_usage = player_usage.merge(player_stats, on="Player")

    return player_usage

# Process each dataset
for i, (ages, player_usage, multi_teams, goals) in enumerate(zip(ages_list, player_usage_list, multi_teams_list, goals_list)):
    processed_data = process_data(ages, player_usage, multi_teams, goals)
    output_filename = f'processed_players_{2022 + i}.csv'
    processed_data.to_csv(output_filename, index=False)
    print(f'Dataset for {2022 + i} processed and saved as {output_filename}')
    
    
    # Load the processed datasets
processed_2022 = pd.read_csv('processed_players_2022.csv')
processed_2023 = pd.read_csv('processed_players_2023.csv')
processed_2024 = pd.read_csv('processed_players_2024.csv')

# Add a column to identify the year
processed_2022['Year'] = 2022
processed_2023['Year'] = 2023
processed_2024['Year'] = 2024

# Combine the datasets into a single DataFrame
all_years_df = pd.concat([processed_2022, processed_2023, processed_2024], ignore_index=True).drop_duplicates()

# Save the combined DataFrame to a new CSV file (optional)
all_years_df.to_csv('combined_players_2022_2024.csv', index=False)

# # Example comparison: Compare TOI for a specific player across years
player_name = 'Chandler Stephenson'

player_data = all_years_df[all_years_df['Player'] == player_name]

print(player_data[['Player', 'Year', 'GP', 'TOI', 'team_TOI', 'QoCF', 'QoCD', 'QoTF', 'QoTD', 'toughest_min', 'Goals']])

#all_years_df.head()

C:\Users\kjcs2\AppData\Local\Temp\ipykernel_19248\4294713429.py:88: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pivoted_df = pivoted_df.fillna(0)
C:\Users\kjcs2\AppData\Local\Temp\ipykernel_19248\4294713429.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pivot_competition_f = pivot_competition_f.fillna(0)
C:\Users\kjcs2\AppData\Local\Temp\ipykernel_19248\4294713429.py:127: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pivot_competition_d = pivot_competition_d.fillna(0)

Dataset for 2022 processed and saved as processed_players_2022.csv

C:\Users\kjcs2\AppData\Local\Temp\ipykernel_19248\4294713429.py:88: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pivoted_df = pivoted_df.fillna(0)
C:\Users\kjcs2\AppData\Local\Temp\ipykernel_19248\4294713429.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pivot_competition_f = pivot_competition_f.fillna(0)
C:\Users\kjcs2\AppData\Local\Temp\ipykernel_19248\4294713429.py:127: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pivot_competition_d = pivot_competition_d.fillna(0)

Dataset for 2023 processed and saved as processed_players_2023.csv

C:\Users\kjcs2\AppData\Local\Temp\ipykernel_19248\4294713429.py:88: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pivoted_df = pivoted_df.fillna(0)
C:\Users\kjcs2\AppData\Local\Temp\ipykernel_19248\4294713429.py:126: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pivot_competition_f = pivot_competition_f.fillna(0)
C:\Users\kjcs2\AppData\Local\Temp\ipykernel_19248\4294713429.py:127: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pivot_competition_d = pivot_competition_d.fillna(0)

Dataset for 2024 processed and saved as processed_players_2024.csv
                   Player  Year  GP      TOI  team_TOI   QoCF   QoCD    QoTF  \
53    Chandler Stephenson  2022  79  1525.12   1525.12  95.29  67.87  100.00
392   Chandler Stephenson  2023  81  1540.38   1540.38  91.51  66.82  100.00
1212  Chandler Stephenson  2024  75  1386.27   1386.27  78.49  56.83   93.33

       QoTD  toughest_min  Goals
53    71.43        334.59      0
392   71.43        329.76     16
1212  66.67        295.32     16

In [15]:
all_years_df=all_years_df.drop(columns=['Team 1_x', 'Team 2_x', 'Team 3_x','Team 1_y', 'Team 2_y', 'Team 3_y' ])
all_years_df.head()

,Player,Team,Position,GP,TOI,Age,atoi,total_percentile,Skater,team_gp,team_TOI,team_atoi,adj_toi,QoTF,QoTD,adj_toi 1_x,adj_toi 2_x,adj_toi 3_x,QoCF,QoCD,team_no,team_count,adj_toi 1_y,adj_toi 2_y,adj_toi 3_y,QoCF 1,QoCF 2,QoCF 3,QoTF 1,QoTF 2,QoTF 3,QoCD 1,QoCD 2,QoCD 3,QoTD 1,QoTD 2,QoTD 3,toughest_min,Goals,Total Assists,First Assists,Second Assists,Total Points,IPP,Shots,SH%,ixG,iCF,iHDCF,Rush Attempts,Rebounds Created,Giveaways,Takeaways,Hits,Hits Taken,Shots Blocked,Faceoffs %,CF,CA,GF,GA,GF%,xGF,xGA,HDGF%,PDO,Year
0,Brent Burns,S.J,D,82,2144.03,39.0,26.15,100.00,D,82.0,2144.03,26.15,2144.30,100.0,100.0,NaN,NaN,NaN,100.0,100.00,1,S.J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400.00,1,1,0,1,2,22.22,19,5.26,0.44,51,1,1,4,6,6,6,9,12,-,1940,2260,115,127,47.52,101.95,126.92,46.15,1.000,2022
1,Victor Hedman,T.B,D,82,2052.43,33.0,25.03,99.85,D,82.0,2052.43,25.03,2052.46,100.0,100.0,NaN,NaN,NaN,100.0,99.55,1,T.B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399.55,1,2,1,1,3,100.00,10,10.00,0.43,18,1,0,1,3,1,8,12,7,-,2161,1680,160,101,61.30,129.30,95.11,59.69,1.022,2022
2,Roman Josi,NSH,D,80,2043.78,34.0,25.55,99.55,D,80.0,2043.78,25.55,2044.00,100.0,100.0,NaN,NaN,NaN,100.0,98.65,1,NSH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,398.65,0,1,1,0,1,20.00,8,0.00,0.45,26,1,0,2,4,0,3,12,10,-,2255,1819,152,94,61.79,117.69,94.71,62.02,1.033,2022
3,Cale Makar,COL,D,77,1976.43,25.0,25.67,99.25,D,77.0,1976.43,25.67,1976.59,100.0,100.0,NaN,NaN,NaN,100.0,97.73,1,COL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,397.73,2,4,1,3,6,75.00,24,8.33,1.30,59,4,1,7,5,9,5,17,15,-,2386,1629,163,75,68.49,137.45,86.59,63.46,1.041,2022
4,Alex Pietrangelo,VGK,D,80,1971.58,34.0,24.64,99.10,D,80.0,1971.58,24.64,1971.20,100.0,100.0,NaN,NaN,NaN,100.0,97.29,1,VGK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,397.29,0,0,0,0,0,0.00,10,0.00,1.33,32,2,0,5,3,2,7,20,15,-,2083,1888,104,102,50.49,113.13,107.91,48.21,0.987,2022